type tools\analysis\ask.py
type tools\analysis\api\get_llm_context.py
type tools\analysis\api\inspect_symbol.py
type tools\analysis\api\oracle_router.py
type tools\analysis\api\query_entry.py
type tools\analysis\api\query_reasoning.py
type tools\analysis\assessor\assessor.py
type tools\analysis\assessor\query_session.py
type tools\analysis\audit\symbol_audit.py
type tools\analysis\classification\classify_references.py
type tools\analysis\context\build_context_bundle.py
type tools\analysis\context\build_context_packet.py
type tools\analysis\context\context_packet.py
type tools\analysis\context\expand_context_from_graph.py
type tools\analysis\context\pipeline_guard.py
type tools\analysis\context\render_context_for_llm.py
type tools\analysis\contracts\analysis_contract.py
type tools\analysis\contracts\classification_contract.py
type tools\analysis\contracts\contract_drift_classifier.py
type tools\analysis\contracts\contract_health_aggregator.py
type tools\analysis\contracts\contract_lifecycle.py
type tools\analysis\contracts\contract_map.py
type tools\analysis\contracts\contract_observer.py
type tools\analysis\contracts\contract_types.py
type tools\analysis\contracts\contract_validator.py
type tools\analysis\contracts\failure_contract.py
type tools\analysis\contracts\load_contract.py
type tools\analysis\contracts\parse_contract.py
type tools\analysis\contracts\persist_contract_violations.py
type tools\analysis\contracts\representation_contract.py
type tools\analysis\contracts\scan_contract.py
type tools\analysis\contracts\semantic_pipeline_contract.py
type tools\analysis\core\pathing.py
type tools\analysis\engine\db_resolver.py
type tools\analysis\engine\engine_evaluation_snapshot.py
type tools\analysis\engine\engine_logger.py
type tools\analysis\engine\engine_snapshot.py
type tools\analysis\engine\engine_snapshot_diff.py
type tools\analysis\engine\invariants.py
type tools\analysis\engine\parity_contract.py
type tools\analysis\engine\pipeline_dependency_tracer.py
type tools\analysis\engine\responsibility_map.py
type tools\analysis\engine\responsibility_snapshot.py
type tools\analysis\engine\run_engine.py
type tools\analysis\engine\structural_parity_diff.py
type tools\analysis\graph\build_dependency_graph.py
type tools\analysis\graph\context_classification.py
type tools\analysis\graph\dependency_graph.py
type tools\analysis\graph\edge_semantics.py
type tools\analysis\graph\evaluation_snapshot.py
type tools\analysis\graph\graph_builder.py
type tools\analysis\graph\module_resolution.py
type tools\analysis\graph\project_context.py
type tools\analysis\graph\project_graph_context.py
type tools\analysis\graph\reachability_stage.py
type tools\analysis\graph\route_trace.py
type tools\analysis\graph\runtime_resolution.py
type tools\analysis\graph\semantic_candidate_builder.py
type tools\analysis\graph\semantic_identity_contract.py
type tools\analysis\graph\semantic_observation.py
type tools\analysis\graph\semantic_roles.py
type tools\analysis\graph\symbol_classifier.py
type tools\analysis\graph\symbol_identity.py
type tools\analysis\graph\symbol_index.py
type tools\analysis\graph\symbol_resolution.py
type tools\analysis\graph\symbol_resolution_engine.py
type tools\analysis\graph\symbol_router.py
type tools\analysis\graph\visualize_dependency_graph.py
type tools\analysis\graph\visualize_local_graph.py
type tools\analysis\identity\edge_identity.py
type tools\analysis\identity\symbol_identity.py
type tools\analysis\ingestion\ast_traversal.py
type tools\analysis\ingestion\build_file_analysis.py
type tools\analysis\ingestion\extract_symbols.py
type tools\analysis\ingestion\parse_ast.py
type tools\analysis\ingestion\scan_project_files.py
type tools\analysis\inspection\explain_file.py
type tools\analysis\inspection\system_shape.py
type tools\analysis\inspection\meta\system_self_model.py
type tools\analysis\metrics\extract_metrics.py
type tools\analysis\observability\fault_injector.py
type tools\analysis\observability\instruments.py
type tools\analysis\observability\signals.py
type tools\analysis\observability\signal_contract.py
type tools\analysis\oracle\db_oracle.py
type tools\analysis\oracle\edge_semantics.py
type tools\analysis\oracle\edge_view.py
type tools\analysis\oracle\embedding_model.py
type tools\analysis\oracle\persist_query_session.py
type tools\analysis\oracle\router.py
type tools\analysis\oracle\symbol_noise.py
type tools\analysis\persistence\persistence_engine.py
type tools\analysis\query\query_file_analysis.py
type tools\analysis\reducer\reduce.py
type tools\analysis\representation\context_bundle.py
type tools\analysis\representation\semantic_identity.py
type tools\analysis\representation\symbol_environment.py
type tools\analysis\resolution\symbol_origin_resolver.py
type tools\analysis\shared\types.py
type tools\analysis\tests\analysis\fixtures\pipeline_fixture.py
type tools\analysis\tests\debug\db_sanity_check.py
type tools\analysis\tests\fixtures\sample_project\runtime_case.py
type tools\analysis\tests\fixtures\sample_project\sample.py
type tools\analysis\tests\observability\rule_inspector.py
type tools\analysis\tests\observability\system_health.py
type tools\analysis\tests\regression\run_all.py
type tools\analysis\truth\query_ast.py
type tools\analysis\truth\query_compiler.py
type tools\analysis\truth\query_executor.py
type tools\analysis\truth\query_plan.py
type tools\analysis\truth\resolver.py
type tools\analysis\truth\subsystem_view.py
type tools\analysis\truth\views.py
type tools\analysis\utilities\reachable_print_trace.py
type tools\analysis\validation\contract_validation_pass.py
type tools\analysis\validation\system_validator.py
