# src/interfaces.py
from typing import List, Tuple, Dict, Any

class IDungeonCell:
    @property
    def base_type(self) -> int: ...
    @property
    def features(self) -> list: ...
    @property
    def npcs(self) -> list: ...
    @property
    def items(self) -> list: ...
    @property
    def visibility(self) -> dict: ...

class IGameState:
    def get_cell(self, x: int, y: int) -> IDungeonCell: ...
    def get_visible_cells(self) -> List[Tuple[int, int]]: ...
    @property
    def party_position(self) -> Tuple[int, int]: ...
    @property
    def width(self) -> int: ...
    @property
    def height(self) -> int: ...